name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Install dependencies
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      # Build the website
      - name: Build website
        run: npm run build
      # Deploy the website
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
